### ISSUE TITLE
Add a function in order to get all messages since a timestamp

### ISSUE THREAD

**Issue by pilerou** [crisp-im/node-crisp-api#1]
Hi,

It could be great to have a function in order to get all messages since a date (or in a range)
It could be a parameter in getList function.

My use case would be to have a scheduled program which gets all messages since the last launch.
I would get a response containing an array of messages such as 
```
[
{"website_id":"...c3","type":"text","from":"operator","origin":"chat","content":"The message","fingerprint":-333,"user":{"nickname":"My nickename","user_id":"....C4"},"timestamp":1487956507997,"stamped":true,"session_id":"session_e690....a0"}
]
```

**Comment by mywaystar** [comment]
Hello Pierre!

Following your request, I updates the node lib to support this usecase:

Update to **v1.2.2**

And use:

```
CrispClient.websiteConversations.getMessages(WEBSITE_ID, SESSION_ID, {
    timestamp_before : 1488187641699
  })
  .then((messages) => {
    console.log("messages", messages);
  })
```

**Comment by pilerou** [comment]
Hi Baptiste,

And thanks for your reactivity !
Actually, my need would be timestamp_after in order to retrieve new messages.
It seems it's not yet implemented.

Moreover, I would like to retrieve messages for all SESSION_ID of my website.
Is it possible to make the session_id optional ?
