### ISSUE TITLE
Request: Add A People Event

### ISSUE THREAD

**Issue by ArthurBrito** [crisp-im/node-crisp-api#14]
I'd like to use this route using the node wrapper: /website/{website_id}/people/events/{people_id}

This route is available in the REST API: https://docs.crisp.chat/api/v1/#website-website-people-post-1

**Comment by eliottvincent** [comment]
Hello Arthur, you can use `CrispClient.websitePeople.addPeopleEvent(websiteId, peopleId, params)` 😊
Params are described in the REST API doc, here: https://docs.crisp.chat/api/v1/#website-website-people-post-1
