### ISSUE TITLE
node-fetch version is vulnerable

### ISSUE THREAD

**Issue by mpomarole** [crisp-im/node-crisp-api#25]
This package depends on `node-fetch`.
This issue tracks the update that needs to happen to version `node-fetch@^2.6.1`.

The real update would be to update `fbemitter` to version `3.0.0`.

Relevant [Github Advisory Database](https://github.com/advisories/GHSA-w7rc-rwvf-8q5r).

**Comment by mpomarole** [comment]
This https://github.com/crisp-im/node-crisp-api/pull/26 should fix it

**Comment by baptistejamin** [comment]
Thank your for the report.

We will merge this in the coming days.

**Comment by eliottvincent** [comment]
Merged, thanks again!

https://www.npmjs.com/package/node-crisp-api/v/1.12.1
