### ISSUE TITLE
findWithSearch is double encoding the query parameters, which is corrupting the search query in some cases.

### ISSUE THREAD

**Issue by bdevore17** [crisp-im/node-crisp-api#32]
https://github.com/crisp-im/node-crisp-api/blob/5fcba72fe6b73af3104d55c3cc1c48373542176c/lib/resources/WebsiteConversations.js#L61

`got` is already encoding query parameters, so it is harmful to do it ahead of time.

**Comment by bdevore17** [comment]
For example, a search query of `+1` is being encoded into `%252B1` instead of `%2B1`

**Comment by bdevore17** [comment]
@eliottvincent Can you please cut a new release with this fix?

**Comment by eliottvincent** [comment]
Sure!

**Comment by eliottvincent** [comment]
Released version 1.12.3: https://www.npmjs.com/package/node-crisp-api/v/1.12.3
