### ISSUE TITLE
Event not triggering: session:request:initiated 

### ISSUE THREAD

**Issue by dgroechel** [crisp-im/node-crisp-api#39]
I am working on an integration and `session:request:initiated ` is not triggering when a new chat is started. I saw it was brought up in issue: https://github.com/crisp-im/node-crisp-api/issues/17 but no resolution. Other events such as `message:send` are working for me.

Steps done to troubleshoot: 
- Incognito window to start a new chat
- Cleared out all crisp cookies and started a new chat 
- Looked at source and `session:request:initiated ` is included in `DEFAULT_RTM_EVENTS`

Code example:
```js 
const Crisp = require('node-crisp-api')

const TOKEN_KEY = <'TOKEN'>
const TOKEN_IDENTIFIER = <'TOKEN'>

const CrispClient = new Crisp()

console.info('Authenticating...')

CrispClient.authenticateTier("plugin", TOKEN_IDENTIFIER, TOKEN_KEY);

console.info('Listening for events...')

CrispClient.on('session:request:initiated', (message) => {
  console.log("session started", message);
})

```

**Comment by baptistejamin** [comment]
Session:request:initiated is not a chat started event. This event is only used when you manually request to chat with a user from the MagicMap.

**Comment by valeriansaliou** [comment]
No, there’s no such event. You’d need to catch a message:send event from the user and distinguish which one is the first for the session.
