### ISSUE TITLE
Set operator availability

### ISSUE THREAD

**Issue by ehsan-mohammadi** [crisp-im/node-crisp-api#41]
Is there any method implemented to set operator availability?

![Availability](https://user-images.githubusercontent.com/22881814/150754197-dfb8fcd1-df84-4fae-8170-6c8bd9515e97.png)

**Comment by baptistejamin** [comment]
Hello there!

**Comment by baptistejamin** [comment]
No each user needs to set this themselves

**Comment by eliottvincent** [comment]
Hey! This is the route you need to use. It's not implemented in this wrapper as this an internal route.

<img width="1492" alt="Screen Shot 2022-01-24 at 10 18 04" src="https://user-images.githubusercontent.com/24720375/150754913-0fb777f9-8a81-452a-8554-527219688531.png">

**Comment by ehsan-mohammadi** [comment]
@eliottvincent Thank you for your quick response!
