### ISSUE TITLE
Nuxt 3 support?

### ISSUE THREAD

**Issue by eMeRiKa13** [crisp-im/node-crisp-api#45]
Hi,

I'm using Nuxt 3. Adding a library by using `require` is not working anymore. So I can't use this library.

Do you have any plan to update the library?

Thanks

**Comment by eliottvincent** [comment]
Hey! Would you mind elaborating? What is "not working" exactly?

**Comment by eMeRiKa13** [comment]
A quote from this discussion in the Nuxt repo:

> `require` is not supported in Vite, and indeed in general you should avoid using require as Nuxt 3 [targets an ESM native environment](https://v3.nuxtjs.org/concepts/esm). Instead, you use `import` - see https://vitejs.dev/guide/assets.html#importing-asset-as-url.

https://github.com/nuxt/framework/issues/2761#issuecomment-1014860270
