### ISSUE TITLE
_request method does not reject with an Error object

### ISSUE THREAD

**Issue by PastaJ36** [crisp-im/node-crisp-api#46]
This method rejects the promise with a custom object: https://github.com/crisp-im/node-crisp-api/blob/1e6b94476621e7f3a435ae09370c8694955f6a7a/lib/crisp.js#L613-L625

Usually rejects are supplied with an Error object, so it includes stack information: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject#description

I don't think it is a requirement for promise rejects to use an Error instance, but it can be expected by some frameworks.

Our use case is that we just have async function errors pass up to our error monitoring service Sentry. We fixed it now with a custom wrapper that creates an error object when the promise rejects.

I'm not sure if the information in the rejects object is used somewhere else, haven't dug too deep in the code. If you need this extra info you could consider extending the Error object.

**Comment by PastaJ36** [comment]
Thanks for the quick response, it's the reason we love using Crisp! 

Could you elaborate a bit on on why you would need mocked API error objects and why that is bad? The additional rejection body context data is nice, but with async function usage there is not really a nice way to make use of it. This is more of a flaw with JS error handling to be fair.

By the way, I also notice the catch return a resolved promise, not sure if that's intentional. I'm not familiar with Got: https://github.com/crisp-im/node-crisp-api/blob/1e6b94476621e7f3a435ae09370c8694955f6a7a/lib/crisp.js#L586

**Comment by valeriansaliou** [comment]
If you look in the next Promise block, you can see further processing is done, and this becomes a reject() in the end.
