### ISSUE TITLE
Data validation error when sending message

### ISSUE THREAD

**Issue by c-delouvencourt** [crisp-im/node-crisp-api#50]
Hello, 

We have an issue when sending picker message in a conversation, could you help us please ?

The request with : `CrispClient.website.sendMessageInConversation`

<img width="447" alt="Capture d’écran 2023-02-14 à 10 55 16" src="https://user-images.githubusercontent.com/26087186/218701219-be355340-be32-4aad-b9d2-08449441dd34.png">

The response : 

`{
  "reason": "error",
  "message": "invalid_data",
  "code": 400,
  "data": {
    "namespace": "response",
    "message": "Got response error: data.type should be equal to one of the allowed values, data.type should be equal to one of the allowed values, data.type should be equal to one of the allowed values, data.type should be equal to one of the allowed values, data.content should have required property 'text', data.type should be equal to one of the allowed values, data.type should be equal to one of the allowed values, data.type should be equal to one of the allowed values, data should match some schema in anyOf"
  }
}`

**Comment by baptistejamin** [comment]
Hi there

**Comment by baptistejamin** [comment]
Can I ask how you are sending your picker?

**Comment by baptistejamin** [comment]
Are you pushing that message with the SDK?

**Comment by baptistejamin** [comment]
If so, could I see the full part of code relevant to that method?

**Comment by c-delouvencourt** [comment]
Hi Baptiste, we are sending the picker like that :  https://hastebin.com/share/epiwuxeyud.javascript

**Comment by baptistejamin** [comment]
I think the issue is because of the type participant. Try with operator instead.
--
Baptiste Jamin

**Comment by c-delouvencourt** [comment]
Same issue with operator

**Comment by baptistejamin** [comment]
Can you please check all the types according to https://docs.crisp.chat/references/rest-api/v1/#send-a-message-in-conversation ?


--
Baptiste Jamin

**Comment by c-delouvencourt** [comment]
I checked all the types are correct I think there is an error on the validation of the type field on your side

**Comment by eliottvincent** [comment]
There is no error on our side, your payload is invalid.

As stated in our API Reference, the `text` property is mandatory. 
This payload will work (I simply added the `text` property):

```
{
  "type": "picker",
  "from": "operator",
  "origin": "chat",
  "user": {
    "type": "participant",
    "nickname": "Edouard",
    "avatar": "https://i.imgur.com/4hh6oao.jpg"
  },
  "content": {
    "id": "aws_image_picker",
    "text": "Some text here",
    "choices": [
      {
        "value": "Connexion hektor",
        "label": "Connexion hektor",
        "selected": false
      },
      {
        "value": "Activer une passerelle de diffusion",
        "label": "Activer une passerelle de diffusion",
        "selected": false
      },
      {
        "value": "Personnaliser mon profil Hektor",
        "label": "Personnaliser ou modifier mon profil hektor",
        "selected": false
      },
      {
        "value": "exporter un bien ",
        "label": "Problème d'exportation d'un bien",
        "selected": false
      },
      {
        "value": "Autre question",
        "label": "Autre question",
        "selected": false
      }
    ]
  }
}
```
