### ISSUE TITLE
absenece of people_Id on conversation.

### ISSUE THREAD

**Issue by OdapX** [crisp-im/node-crisp-api#60]
Hello,

I use the `getConversation` from the website api, I am noticing the absence of the `people_Id` , according to the docs this field should be returned :

<img width="761" alt="bug" src="https://github.com/crisp-im/node-crisp-api/assets/72660683/1c68f345-a0b3-495b-abe1-2de385cf3df2">

**Comment by valeriansaliou** [comment]
If the conversation has no people identifier then it's not there at all (ie. the conversation object does not have the key `people_id`).
