### ISSUE TITLE
Helpdesk -> List Helpdesk Locale Articles. Parameter order_visits by default (with 0 value) doesn't work correctly

### ISSUE THREAD

**Issue by tiu93** [crisp-im/node-crisp-api#61]
Hello! I am trying to retrieve articles without the order_visits parameter or with order_visits=0. However, I am receiving unsorted records. The required records appear at the beginning of the list but are not sorted among themselves. For example, initially, a record with order=9, then order=2, then order=6, and so on.

**My request:**
https://api.crisp.chat/v1/website/:website_id/helpdesk/locale/:locale/articles/:page_number?order_visits=0

**Comment by eliottvincent** [comment]
Hey!

As of right now it's not possible to sort articles by their `order` property. They can only be sorted by number of visits or by most recently updated.

**Comment by baptistejamin** [comment]
Hey there!

Thank you for your feedback. It has just been implemented on `v8.2.2`
