### ISSUE TITLE
How to pass URI parameters to endpoint?

### ISSUE THREAD

**Issue by timurkhakhalev** [crisp-im/node-crisp-api#62]
HI! I would like to pass some URI parameters for example for this https://docs.crisp.chat/references/rest-api/v1/#list-helpdesk-locale-articles endpoint, but as I can see in code source here https://github.com/crisp-im/node-crisp-api/blob/07b063fb0f40ba3eea21a194bce2cd848385f96b/lib/resources/WebsiteHelpdesk.js#L185C32-L185C32 there are no way to pass URI params. 

Any ways?

upd:
Also it would be nice to have an opportunity:
1.  To select fields in response
2. To get total count of articles or pages in response to paginate them in easy way

**Comment by baptistejamin** [comment]
Hey there!

Thank you for your feedback. It has just been implemented on `v8.2.2`
