### ISSUE TITLE
Not able to call the listPeopleConversations method

### ISSUE THREAD

**Issue by vrochamaia** [crisp-im/node-crisp-api#8]
Hi,

I'm trying to get all the conversations by the a specific user using the following method

`CrispClient.websitePeople.listPeopleConversations(process.env.CRISP_WEB_SITE_ID, people.people_id, 0)`

I'm quite sure that the websiteId and peopleId are correct, but actually I'm receiving an exception like this: `{"reason":"error","message":"not_found"}`. And yes, the peopleId specified have more than one conversation.

Besides that, the method is not on the README.md file of this repository, but it's on the source code as I already checked.

Am I doing something wrong? Thanks in advance.

**Comment by valeriansaliou** [comment]
Hi again. Found an issue in the route as expected. Fixed & updated the library on NPMJS, you can bump to `v1.8.1` and let me know if that works for you.

**Comment by vrochamaia** [comment]
Yeah, it's working now! Thanks.
