### ISSUE TITLE
Node crashes if response is not JSON

### ISSUE THREAD

**Issue by priyankinfinnov** [crisp-im/node-crisp-api#9]
I am using v1.7.1 and **occasionally** I see the below error - 
______________________________________
SyntaxError: Unexpected token < in JSON at position 0
at Object.parse (native)
at Request._callback (/home/ec2-user/repo/node_modules/node-crisp-api/lib/crisp.js:354:25)
______________________________________
Which can happen when any request returns an error or statusCode >= 400 **without a json response**.
As of posting the line number is 351 at file https://github.com/crisp-im/node-crisp-api/blob/master/lib/crisp.js 

Possible fix  - The JSON.parse(body) should be within a try-catch block.

PS: I understand the latest version is 1.8.1, but when I check the latest code, this issue is not addressed.

**Comment by valeriansaliou** [comment]
Do you have the full server crash log? I don't see any case where responses from our servers will not be JSON, except Cloudflare edge errors. Can we see the response that makes things crash?

**Comment by priyankinfinnov** [comment]
I have full crash logs for my node process, but it does not have any logs from the crisp module, so it won't help here.

Do you return JSON for rate-limits also? [coz, I doubt my app is getting rate limited, crashes only happen at peak traffic times]

Ill manually add a try catch with a log for data, so that we can debug further.

But, to reduce crashes you can add the try catch [it will be safer for everybody, also at the time of service failure/outage, non JSON response might come]

**Comment by valeriansaliou** [comment]
Processing this yep.

**Comment by valeriansaliou** [comment]
`v1.8.2` released on NPM, which fixes this bug. Thanks 👍

**Comment by priyankinfinnov** [comment]
That is fast, thanks!
I'll update this thread if I find the crashing data response.
